version: '3'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --init-file /scripts/init-script.sql
    volumes:
      - ./init.sql:/scripts/init-script.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bluepillcrm
    ports:
      - "3306:3306"
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "5137:5137"
    environment:
      - DOTNET_URLS=http://+:5137
    depends_on:
      - mysql
