name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pull Data
        uses: actions/checkout@v2
      
      - name: Build Docker image
        run: sudo docker compose up -d
