name: CI/CD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pull Data from main branch
        uses: actions/checkout@v2

      - name: Stop Docker container (Backend)
        run: sudo docker stop crmproject-app-1
        

      - name: Remove Docker container (Backend)
        run: sudo docker rm crmproject-app-1

      - name: Build Docker container
        run: sudo docker compose build
          
      - name: Run Docker container
        run: sudo docker compose up -d


