name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pull Data
        uses: actions/checkout@v2

      - name: Stop Docker container
        run:
        sudo docker stop crmproject-app-1
        sudo docker stop crmproject-mysql-1

      - name: Remove Docker container
        run:
        sudo docker rm crmproject-app-1
        sudo docker rm crmproject-mysql-1

      - name: Build and Run Docker container
        run:
          sudo docker compose build
          sudo docker compose up -d
